# tasks file for sendmail
---
- name: Sending an e-mail using Gmail SMTP servers
  mail:
          host: smtp.gmail.com
          port: 587
          username: " {{ myusername }} "
          password: " {{ mypassword }} "
          to: " {{ Reciever_name }} <{{ Reciever_username }}> "
          subject: " {{ sub }} "
          body:
                  - " {{ ansible_hostname }} "
                  - " {{info}} "
  delegate_to: localhost





















